# -------------------------------------------------- #
# This file is autogenerated by pioasm; do not edit! #
# -------------------------------------------------- #

import rp2
from machine import Pin
# ------------ #
# irda_uart_tx #
# ------------ #

@rp2.asm_pio(autopull=False, set_init=rp2.PIO.OUT_LOW, out_shiftdir=rp2.PIO.SHIFT_LEFT)
def irda_uart_tx():
    wrap_target()
    pull(block)                           # 0
    set(pins, 1)                     [2]  # 1
    set(pins, 0)                     [9]  # 2
    set(y, 7)                             # 3
    label("4")
    out(x, 1)                             # 4
    jmp(not_x, "9")                       # 5
    nop()                            [12] # 6
    jmp(y_dec, "4")                       # 7
    jmp("12")                             # 8
    label("9")
    set(pins, 1)                     [2]  # 9
    set(pins, 0)                     [9]  # 10
    jmp(y_dec, "4")                       # 11
    label("12")
    set(pins, 0)                     [14] # 12
    wrap()


# ----------------- #
# irda_uart_rx_9600 #
# ----------------- #

@rp2.asm_pio(autopush=False, in_shiftdir=rp2.PIO.SHIFT_LEFT)
def irda_uart_rx_9600():
    wrap_target()
    label("0")
    wait(0, pin, 0)                  [5]  # 0
    jmp(pin, "0")                         # 1
    nop()                            [3]  # 2
    set(y, 7)                             # 3
    label("4")
    set(x, 24)                            # 4
    label("5")
    jmp(x_dec, "5")                  [23] # 5
    nop()                            [16] # 6
    in_(pins, 1)                     [5]  # 7
    jmp(y_dec, "4")                       # 8
    set(x, 24)                            # 9
    label("10")
    jmp(x_dec, "10")                 [23] # 10
    nop()                            [16] # 11
    jmp(pin, "14")                        # 12
    jmp("0")                              # 13
    label("14")
    push(block)                           # 14
    wrap()


# ------------------- #
# irda_uart_rx_115200 #
# ------------------- #

@rp2.asm_pio(autopush=False, in_shiftdir=rp2.PIO.SHIFT_LEFT)
def irda_uart_rx_115200():
    wrap_target()
    label("0")
    wait(0, pin, 0)                  [11] # 0
    jmp(pin, "0")                         # 1
    nop()                            [8]  # 2
    set(y, 7)                             # 3
    label("4")
    set(x, 9)                             # 4
    label("5")
    jmp(x_dec, "5")                  [7]  # 5
    nop()                            [4]  # 6
    in_(pins, 1)                     [12] # 7
    jmp(y_dec, "4")                       # 8
    set(x, 9)                             # 9
    label("10")
    jmp(x_dec, "10")                 [7]  # 10
    nop()                            [4]  # 11
    jmp(pin, "14")                        # 12
    jmp("0")                              # 13
    label("14")
    push(block)                           # 14
    wrap()


